spring:
  application:
    name: DataManager
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  profiles:
    active: #spring.profiles.active#
server:
  port: 9080
swagger:
  basePackage: com.shark.application
logging:
  level:
    root: info
---
debug: false
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/base
    username: root
    password: root
    hikari:
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10